title: Vikas Vyas # your name (or website title) here
logo: /assets/img/Vikas-Photo.JPG # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Vikas, I'm a research analyst at a tech company functioning in the healthcare space. I have expertise in qualitative and quantitve analysis, competitive intelligence, and market tracking.
  <br><br>
  My hard skills include: SQL, Tableau, Excel/Google Sheets, and Python. 
  <br><br>
  <a href="https://www.linkedin.com/in/vikasvyas11/">View My LinkedIn Profile</a> 
showdownloads: true  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
